"""Ports required by the current application slice."""

from datetime import datetime
from typing import Protocol

from job_hunter.domain.ids import (
    CandidateProfileId,
    EvidenceItemId,
    EvidenceVersionId,
    JobId,
    JobVersionId,
    QuickScreenResultId,
    RequirementId,
    SourceReferenceId,
    SourceSnapshotId,
    TriageDecisionId,
)
from job_hunter.domain.jobs import Job, JobVersion, SourceSnapshot
from job_hunter.domain.knowledge import CandidateProfile, EvidenceItem, EvidenceItemVersion
from job_hunter.domain.screening import JobTriageRecord, ParsedRequirement, QuickScreenResult


class Clock(Protocol):
    def now(self) -> datetime: ...


class IdGenerator(Protocol):
    def new_job_id(self) -> JobId: ...

    def new_job_version_id(self) -> JobVersionId: ...

    def new_source_snapshot_id(self) -> SourceSnapshotId: ...

    def new_source_reference_id(self) -> SourceReferenceId: ...

    def new_candidate_profile_id(self) -> CandidateProfileId: ...

    def new_evidence_item_id(self) -> EvidenceItemId: ...

    def new_evidence_version_id(self) -> EvidenceVersionId: ...

    def new_requirement_id(self) -> RequirementId: ...

    def new_quick_screen_result_id(self) -> QuickScreenResultId: ...

    def new_triage_decision_id(self) -> TriageDecisionId: ...


class JobRepository(Protocol):
    def list_jobs(self) -> tuple[Job, ...]: ...

    def get_job(self, job_id: JobId) -> Job: ...

    def get_version(self, version_id: JobVersionId) -> JobVersion: ...

    def get_snapshot(self, snapshot_id: SourceSnapshotId) -> SourceSnapshot: ...

    def add_job(self, job: Job) -> None: ...

    def save_job(self, job: Job) -> None: ...

    def add_version(self, version: JobVersion) -> None: ...

    def add_snapshot(self, snapshot: SourceSnapshot) -> None: ...


class CandidateKnowledgeRepository(Protocol):
    def list_profiles(self) -> tuple[CandidateProfile, ...]: ...

    def get_active_profile_id(self) -> CandidateProfileId | None: ...

    def get_profile(self, profile_id: CandidateProfileId) -> CandidateProfile: ...

    def get_active_profile(self) -> CandidateProfile: ...

    def add_profile(self, profile: CandidateProfile) -> None: ...

    def get_evidence(self, evidence_id: EvidenceItemId) -> EvidenceItem: ...

    def list_evidence(self) -> tuple[EvidenceItem, ...]: ...

    def get_evidence_version(self, version_id: EvidenceVersionId) -> EvidenceItemVersion: ...

    def add_evidence(self, evidence: EvidenceItem) -> None: ...

    def save_evidence(self, evidence: EvidenceItem) -> None: ...

    def add_evidence_version(self, version: EvidenceItemVersion) -> None: ...


class ScreeningRepository(Protocol):
    def get_requirement(self, requirement_id: RequirementId) -> ParsedRequirement: ...

    def list_requirements(self, job_version_id: JobVersionId) -> tuple[ParsedRequirement, ...]: ...

    def add_requirements(self, requirements: tuple[ParsedRequirement, ...]) -> None: ...

    def get_quick_screen_result(self, result_id: QuickScreenResultId) -> QuickScreenResult: ...

    def get_latest_quick_screen_result(self, job_id: JobId) -> QuickScreenResult: ...

    def list_quick_screen_results(self, job_id: JobId) -> tuple[QuickScreenResult, ...]: ...

    def add_quick_screen_result(self, result: QuickScreenResult) -> None: ...

    def add_triage_record(self, record: JobTriageRecord) -> None: ...

    def list_triage_records(self, job_id: JobId) -> tuple[JobTriageRecord, ...]: ...


class UnitOfWork(Protocol):
    @property
    def jobs(self) -> JobRepository: ...

    @property
    def knowledge(self) -> CandidateKnowledgeRepository: ...

    @property
    def screening(self) -> ScreeningRepository: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
